import { TrackerDataSnapshot } from "./trackerTypes";

const now = new Date();
const iso = (date: Date) => date.toISOString();

export const defaultTrackerData: TrackerDataSnapshot = {
  platforms: [
    { id: "pc", name: "PC" },
    { id: "ps5", name: "PlayStation 5" },
    { id: "xbox", name: "Xbox Series" },
    { id: "switch", name: "Nintendo Switch" },
  ],
  games: [
    {
      id: "stellar-odyssey",
      title: "Stellar Odyssey",
      description:
        "Chart a course through a handcrafted galaxy in this narrative-driven space RPG featuring tactical ship combat and meaningful crew relationships.",
      genres: ["RPG", "Adventure"],
      platforms: ["pc", "ps5", "xbox"],
      releaseDate: "2023-10-12",
      developer: "Luminous Forge",
      coverImage: "/images/games/stellar-odyssey.jpg",
      gallery: [
        "/images/games/stellar-odyssey-1.jpg",
        "/images/games/stellar-odyssey-2.jpg",
        "/images/games/stellar-odyssey-3.jpg",
      ],
      averagePlaytime: 1260,
    },
    {
      id: "echoes-of-ember",
      title: "Echoes of Ember",
      description:
        "A co-operative roguelite where you and your allies weave elemental magic to restore balance to a world frozen in time.",
      genres: ["Roguelite", "Co-op"],
      platforms: ["pc", "ps5"],
      releaseDate: "2024-02-21",
      developer: "Silver Petal Studio",
      coverImage: "/images/games/echoes-of-ember.jpg",
      gallery: [
        "/images/games/echoes-of-ember-1.jpg",
        "/images/games/echoes-of-ember-2.jpg",
        "/images/games/echoes-of-ember-3.jpg",
      ],
      averagePlaytime: 540,
    },
    {
      id: "neon-sprint",
      title: "Neon Sprint",
      description:
        "Dash through synthwave cityscapes at breakneck speed while chaining trick combos in this precision racing platformer.",
      genres: ["Racing", "Arcade"],
      platforms: ["pc", "switch"],
      releaseDate: "2022-08-05",
      developer: "Photon Drift",
      coverImage: "/images/games/neon-sprint.jpg",
      gallery: [
        "/images/games/neon-sprint-1.jpg",
        "/images/games/neon-sprint-2.jpg",
        "/images/games/neon-sprint-3.jpg",
      ],
      averagePlaytime: 300,
    },
    {
      id: "forgotten-depths",
      title: "Forgotten Depths",
      description:
        "Descend alone or with friends through procedurally generated caverns where dynamic hazards keep every delve unpredictable.",
      genres: ["Action", "Survival"],
      platforms: ["pc", "xbox"],
      releaseDate: "2023-05-30",
      developer: "Obsidian Reef",
      coverImage: "/images/games/forgotten-depths.jpg",
      gallery: [
        "/images/games/forgotten-depths-1.jpg",
        "/images/games/forgotten-depths-2.jpg",
        "/images/games/forgotten-depths-3.jpg",
      ],
      averagePlaytime: 780,
    },
  ],
  achievements: [
    {
      id: "stellar-story",
      gameId: "stellar-odyssey",
      name: "Seasoned Captain",
      description: "Complete the Stellar Voyage campaign on any difficulty.",
      xp: 50,
      rarity: "rare",
    },
    {
      id: "stellar-crew",
      gameId: "stellar-odyssey",
      name: "Crew Confidant",
      description: "Max out loyalty with three unique crew members.",
      xp: 30,
      rarity: "uncommon",
    },
    {
      id: "ember-ascendant",
      gameId: "echoes-of-ember",
      name: "Ascendant",
      description: "Clear floor 15 without a team member falling.",
      xp: 40,
      rarity: "legendary",
    },
    {
      id: "neon-combo",
      gameId: "neon-sprint",
      name: "Combo Conductor",
      description: "Maintain an S-tier combo for 90 seconds.",
      xp: 20,
      rarity: "rare",
    },
    {
      id: "depths-delver",
      gameId: "forgotten-depths",
      name: "Deep Delver",
      description: "Reach biome 6 without returning to camp.",
      xp: 35,
      rarity: "rare",
    },
  ],
  achievementUnlocks: [
    {
      id: "unlock-1",
      achievementId: "stellar-story",
      userId: "demo-user",
      unlockedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24 * 6)),
    },
    {
      id: "unlock-2",
      achievementId: "neon-combo",
      userId: "demo-user",
      unlockedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24 * 2)),
    },
  ],
  lists: [
    { id: "list-backlog", userId: "demo-user", name: "Backlog", type: "default" },
    { id: "list-playing", userId: "demo-user", name: "Playing", type: "default" },
    { id: "list-completed", userId: "demo-user", name: "Completed", type: "default" },
    { id: "list-coop", userId: "demo-user", name: "Co-op Nights", type: "custom" },
  ],
  listItems: [
    {
      id: "item-1",
      listId: "list-playing",
      gameId: "stellar-odyssey",
      status: "Playing",
      progress: 0.45,
      playtimeMinutes: 980,
      lastPlayedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 18)),
      isInstalled: true,
    },
    {
      id: "item-2",
      listId: "list-backlog",
      gameId: "echoes-of-ember",
      status: "Backlog",
      progress: 0.05,
      playtimeMinutes: 120,
      lastPlayedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 48)),
      isInstalled: false,
    },
    {
      id: "item-3",
      listId: "list-completed",
      gameId: "neon-sprint",
      status: "Completed",
      progress: 1,
      playtimeMinutes: 360,
      lastPlayedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10)),
      isInstalled: false,
    },
    {
      id: "item-4",
      listId: "list-coop",
      gameId: "forgotten-depths",
      status: "Playing",
      progress: 0.32,
      playtimeMinutes: 420,
      lastPlayedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 72)),
      isInstalled: true,
    },
  ],
  playSessions: [
    {
      id: "session-1",
      userId: "demo-user",
      gameId: "stellar-odyssey",
      minutes: 95,
      playedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24)),
    },
    {
      id: "session-2",
      userId: "demo-user",
      gameId: "echoes-of-ember",
      minutes: 60,
      playedAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 12)),
    },
  ],
  activity: [
    {
      id: "activity-1",
      userId: "demo-user",
      type: "achievement",
      title: "Unlocked Seasoned Captain",
      description: "You completed the Stellar Voyage campaign.",
      createdAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24 * 6)),
      relatedGameId: "stellar-odyssey",
      relatedAchievementId: "stellar-story",
    },
    {
      id: "activity-2",
      userId: "demo-user",
      type: "play",
      title: "95 minutes in Stellar Odyssey",
      description: "Logged a new play session.",
      createdAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 24)),
      relatedGameId: "stellar-odyssey",
    },
    {
      id: "activity-3",
      userId: "demo-user",
      type: "list",
      title: "Moved Echoes of Ember to Backlog",
      description: "Organised your Backlog list.",
      createdAt: iso(new Date(now.getTime() - 1000 * 60 * 60 * 48)),
      relatedGameId: "echoes-of-ember",
    },
  ],
};
