openapi: 3.1.0
info:
  title: Checkout Webhook Function
  version: 1.0.0
paths:
  /checkout/webhook:
    post:
      summary: Update an order after an external payment event
      operationId: checkoutWebhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [order_id, status]
              properties:
                order_id:
                  type: string
                  format: uuid
                status:
                  type: string
                  enum: [paid, failed]
                payment_reference:
                  type: string
                provider_event:
                  type: string
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      order_id:
                        type: string
                        format: uuid
                      status:
                        type: string
                        enum: [paid, failed]
        '401':
          description: Unauthorized webhook
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '4XX':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '5XX':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
          required: [code, message]
